### ISSUE TITLE
Start Up Error

### ISSUE THREAD

**Issue by maverickjoy** [FerreroJeremy/ln2sql#31]
There is an error while starting the project in python3
 -  On running the file ln2sql.py

**Comment by shashank88** [comment]
Hi,

What's the error?

Thanks

**Comment by maverickjoy** [comment]
- On running setup.py (I guess this would be the same error which would reflect on running it from pypi at the time of installation)
            Traceback (most recent call last):
              File "setup.py", line 13, in <module>
                setup_requires=['pytest'],
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 128, in setup
                _install_setup_requires(attrs)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/dist.py", line 455, in fetch_build_eggs
                replace_conflicting=True,
              File "/home/vikram/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 866, in resolve
                replace_conflicting=replace_conflicting
              File "/home/vikram/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1146, in best_match
                return self.obtain(req, installer)
              File "/home/vikram/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1158, in obtain
                return installer(requirement)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
                return cmd.easy_install(req)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
                not self.always_copy, self.local_index
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/package_index.py", line 656, in fetch_distribution
                self.find_packages(requirement)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/package_index.py", line 489, in find_packages
                self.scan_url(self.index_url + requirement.unsafe_name + '/')
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/package_index.py", line 829, in scan_url
                self.process_url(url, True)
              File "/home/vikram/.local/lib/python3.5/site-packages/setuptools/package_index.py", line 359, in process_url
                page = f.read()
              File "/usr/lib/python3.5/http/client.py", line 461, in read
                s = self._safe_read(self.length)
              File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
                raise IncompleteRead(b''.join(s), amt)
            http.client.IncompleteRead: IncompleteRead(15618 bytes read, 4431 more expected)


- On running `python3 ln2sql.py -d database/city.sql -l lang/english.csv -j output.json -i "how many city there are in which the employee name is similar to aman ?"`
  (I even tried to remove the relative import of '.' as in the same directory but then again some other errors)
              Traceback (most recent call last):
              File "ln2sql.py", line 4, in <module>
                from .database import Database
              SystemError: Parent module '' not loaded, cannot perform relative import
