### ISSUE TITLE
Unable to use thesaurus file

### ISSUE THREAD

**Issue by LawnboyMax** [FerreroJeremy/ln2sql#41]
### Issue
I am unable to replicate the example from README but with `-t thesaurus_store/th_english.dat` flag (works fine without it): 
```python
python -m ln2sql.main -d database_store/city.sql -l lang_store/english.csv -t thesaurus_store/th_english.dat -i "Count how many city there are with the name blob?"
```

### Error Message
```python
Traceback (most recent call last):
  File "c:\users\user\appdata\local\continuum\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\continuum\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\desktop\projects\natural_language_sql\ln2sql-master\ln2sql\main.py", line 26, in <module>
    main()
  File "c:\users\user\desktop\projects\natural_language_sql\ln2sql-master\ln2sql\main.py", line 23, in main
    ).get_query(args.sentence)
  File "c:\users\user\desktop\projects\natural_language_sql\ln2sql-master\ln2sql\ln2sql.py", line 44, in get_query
    queries = self.parser.parse_sentence(input_sentence, self.stopwordsFilter)
  File "c:\users\user\desktop\projects\natural_language_sql\ln2sql-master\ln2sql\parser.py", line 711, in parse_sentence
    input_word_list[i] in self.database_object.get_table_by_name(table_name).equivalences):
TypeError: argument of type 'NoneType' is not iterable
```

### System info and versions

Python 3.6.1
Windows 10
ln2sql version: 0.2

**Comment by FerreroJeremy** [comment]
The pypi version is really not updated; it does not include most of features of the github version (see @shashank88 for more info).
Sorry for the inconvenience.
